language: python
python:
  - 2.7
install:
  - python setup.py install
  - mkdir ~/.python-eggs
  - chmod og-wx ~/.python-eggs
  - pip install codecov
script:
  - python setup.py test
  - ./coverage-run.sh
sudo: false
after_success:
  - codecov
